### ISSUE TITLE
Composer.json dependencies need to be updated

### ISSUE THREAD

**Issue by Garethp** [cakephp/orm#10]
The current version of `cakephp/orm` has it's dependencies set to 

``` json
    "require": {
        "cakephp/collection": "~3.0",
        "cakephp/core": "~3.0",
        "cakephp/datasource": "~3.0",
        "cakephp/database": "~3.0",
        "cakephp/event": "~3.0",
        "cakephp/utility": "~3.0",
        "cakephp/validation": "~3.0"
    }
```

But this isn't right. When I updates from `3.1.1` to `3.2.7`, with the command `composer update cakephp/orm`, I found myself getting errors from `cakephp/datasource` and `cakephp/database`.

`cakephp/orm/Query` implements `cakephp/datasource/QueryInterface`, which doesn't exist in `cakephp/datasource 3.1.1`, and somewhere (I didn't catch the error) `cakephp/orm` also relies on `cakephp/database/Schema/Table::typeMap()` which doesn't exist until `cakephp/database 3.1.4`.

However, since the `composer.json` only requires all packages at `~3.0`, they didn't get updated with `cakephp/orm`, causing errors on update. Updating the version dependencies to match what the package actually depends on would fix this issue. The world around I used was to do a `composer remove cakephp/orm` and then do a `composer require cakephp/orm`

**Comment by renan** [comment]
Can be reproduced with:

```
composer init --no-interaction
composer require cakephp/datasource:3.0
composer require cakephp/orm:3.2
```

ORM v3.2 is installed without complaints and Datasource is not updated.
