### ISSUE TITLE
README incorrect info

### ISSUE THREAD

**Issue by kinkaz** [cakephp/orm#11]
Hi,

As pointed out in this topic : http://discourse.cakephp.org/t/orm-cache-metadata-issue/1071/4 there is a problem with the default Configuration in the README.

The parameter 'cacheMetaData' should be 'cacheMetadata'. 

I don't know if packagist.org pulls the README from Github, but if not, you may want to change it also there because that's where I used it :-)

Thank you,

kinkaz

**Comment by antograssiot** [comment]
@kinkaz do you want to open a PR against cakephp/cakephp

**Comment by ADmad** [comment]
I have fixed the README. The readme on packagist will be updated when a new release is done.
