### ISSUE TITLE
Change i18n package dependency from suggest to require

### ISSUE THREAD

**Issue by devkev16** [cakephp/orm#12]
Hi,

first of all I'm sorry if this is the wrong repo to file a bug report because of the read-only mark. 

Nevertheless:
After I installed cakephp\orm package and setup a mysql connection I experienced missing dependency error for Cake\i18n\Date class. 

The documentation at http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration states that Cake\i18n\Date will be used as a return value for columns of the type "DATE".

Have I overlooked something or is Cake\i18n really a critical dependency and should be moved to the require block in composer.json (Because if I think I some use an ORM-Package it should handle Date-Operations out of the box)?

**Comment by markstory** [comment]
`cake/i18n` shouldn't be a hard requirement of the orm package. If `cake/i18n` isn't installed the ORM will fallback to using PHP's built-in `DateTime` classes. The documentation is generally targeted at the full-stack user as that is the bulk of our user base.

Would it be useful to point this out in the section you linked to?

**Comment by devkev16** [comment]
Yes, I think it would be usefull. 

I also use Cake3 fullstack for other projects than the current and I think a short hint would have been resulted in less headache concerning db/date things.

**Comment by harikt** [comment]
@markstory probably should consider adding some better messages for suggest that would resolve the problem I believe.

See monolog : https://github.com/Seldaek/monolog/blob/58544af7ff9d0c54ef36bc0e4e79330cda751b0e/composer.json#L34

**Comment by markstory** [comment]
Good idea @harikt

**Comment by harikt** [comment]
@markstory I have added some notes to suggest. You can see PR referenced above.
