### ISSUE TITLE
Documentation part missing

### ISSUE THREAD

**Issue by nekkid** [cakephp/orm#15]
Dear all,

the part where to put the Model / Table / Entities files is missing and how to put it in the autoloading.
It is not self explanatory if you are new to CakePHP-ORM and especially not if you don't have any background knowledge of CakePHP.

In this regards I opened an question on Stackoverflow which was correctly answered by the user ndm.
[StackOverflow question](https://stackoverflow.com/questions/51966314/where-to-define-table-entity-classes-when-using-the-standalone-cakephp-orm/51967901#51967901)

It would be nice if you can add this to the documentation :) .

Kind regards,
Marius

**Comment by saeideng** [comment]
1) `readme.md` in https://github.com/cakephp/orm for start to using ORM as standalone package 
2) https://book.cakephp.org/3.0/en/orm.html for more info 
3) you can see ORM examples in https://github.com/cakephp/cakephp/tree/master/tests/TestCase/ORM

**Comment by nekkid** [comment]
1.	As said here it is not writing where to put the table/entity files
2.	Here it is explained HOW to write tables but still not where to put it
3.	This is good for understanding, but it should be stated in the docs, no?

My intention why I mentioned this was to make the Docu more interesting for new uses to start with.

 

Kind regards / Freundliche Grüße,

Marius Treu

 

Von: saeideng <notifications@github.com> 
Gesendet: Freitag, 24. August 2018 15:23
An: cakephp/orm <orm@noreply.github.com>
Cc: nekkid <marius.treu@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [cakephp/orm] Documentation part missing (#15)

 

1.	readme.md in https://github.com/cakephp/orm for start to using ORM as standalone package
2.	https://book.cakephp.org/3.0/en/orm.html for more info
3.	you can see ORM examples in https://github.com/cakephp/cakephp/tree/master/tests/TestCase/ORM

**Comment by saeideng** [comment]
>1)As said here it is not writing where to put the table/entity files
>2)Here it is explained HOW to write tables but still not where to put it

because you no need to  table/entity class :)
`readme` is complete to use 
try bellow code to use ORM without extra class ( table / entity  )
```php
use Cake\Datasource\ConnectionManager;

ConnectionManager::setConfig('default', [
	'className' => 'Cake\Database\Connection',
	'driver' => 'Cake\Database\Driver\Mysql',
	'database' => 'test',
	'username' => 'root',
	'password' => 'secret',
	'cacheMetadata' => true,
	'quoteIdentifiers' => false,
]);
//
use Cake\ORM\Locator\TableLocator;

$locator = new TableLocator();
$articles = $locator->get('Articles');
$entity = $articles->get($id);
echo $entity->title
```

**Comment by markstory** [comment]
@nekkid Where were you hoping to find the information you're looking for?  The [orm intro](https://book.cakephp.org/3.0/en/orm.html) documentation contains an example of where an entity & table class should be saved. Perhaps we are missing links somewhere else though?

**Comment by ndm2** [comment]
@markstory A possible "problem" might be that the Cookbook focuses on the usage in a CakePHP application, ie all examples are using the `App` namespace and assume the default app autoloading accordingly. When used standalone, the ORM will look in the `Model\Table` and `Model\Entity` namespaces, which might not be obvious to people, especially when they're not familiar with CakePHP as a whole.

Maybe it would be good to have a quick start in the repos readme, similar to the quick start in the Cookbooks ORM introduction, showing the expected namespaces for standalone usage, mentioning the difference to in-app usage, and mentioning / linking to how to affect the lookup via the `App.namespace` config. I could imagine that such a head start would make reading the Cookbook easier.

**Comment by harikt** [comment]
@ndm2 good point. When I was working with cakephp @lorenzo helped me to figure out the App.namespace thing. iirc I have documented some where or probably missed. I was digging again on the example but couldn't find the repo. Found another one though : https://github.com/harikt/php-orm-usages/tree/master/cakeorm if anyone need.

**Comment by lorenzo** [comment]
I'll add some words to the readme

**Comment by lorenzo** [comment]
Pull request open: https://github.com/cakephp/cakephp/pull/12504
