### ISSUE TITLE
Cake\I18n\Time is used in TimestampBehavior.php but does not exist in cakephp/orm

### ISSUE THREAD

**Issue by elovin** [cakephp/orm#16]
I get the following error:

[`Error: Class 'Cake\I18n\Time' not found in /ws/vendor/cakephp/orm/Behavior/TimestampBehavior.php:149`](https://github.com/cakephp/orm/blob/eeb330f0a96d10a6f876a748bc3384d2ddb294a0/Behavior/TimestampBehavior.php)

And indeed, the class does not exist in cakephp orm standalone.

Im useing cakephp/orm 3.6.10

**Comment by saeideng** [comment]
This issue was moved to cakephp/cakephp#12630
