### ISSUE TITLE
Breaking change cakephp/database 4.4 vs 4.5

### ISSUE THREAD

**Issue by pimjansen** [cakephp/orm#20]
Hey,

I noticed a breaking change in the upgrade of cakephp/database. Composer audit notified me of a CVE in the lib. I updated the package which gave me the 4.5.4 one in my composer.lock.

This results in my app giving exceptions on missing WRITE_ALL constants. This indicates for me that there is a breaking change since this bump is a minor.

After update cakephp/orm to 4.5.4 as well the issue is resolved. This indicates for me that the constraints are not really ok here since it is an independent package.

I understand that you cant revert stuff and cant do anything about it. But i think it is good to raise this to let you know.

Best
Pim

**Comment by ADmad** [comment]
Issues are accepted against the cakephp/cakephp repo where the code lies, this is just a split package.

**Comment by pimjansen** [comment]
Fair but it still means its a breaking change? A minor upgrade caused issues?

Bit weird to just mark it as, we really do not care

**Comment by ADmad** [comment]
Your related issue https://github.com/cakephp/cakephp/issues/17624 is still open and will be investigated.
