### ISSUE TITLE
Are there any way to retrieve several type of entities from one table object?

### ISSUE THREAD

**Issue by kanonji** [cakephp/orm#4]
## My situation

I have been developing a kind of RPG game.
I am hanging up about modeling and database design for items with CakePHP3 ORM.
### Modeling
- Healing items
- Key items
- Leveling items
- Ticket items

In the game, there are some kind of items.
These can be an Item entity. but I think it is better to split 4 type of entities like above.
Each entity will have few different methods.
### Database design

All items store in an items table.
Healing items and Leveling items have `effect` column which how much healing or leveling up when it is used.
Key items and Ticket items is the same as Healing item except `effect` column.
I have no reason to create tables for each entities.
## What I did

```
class ItemsTable extends Table
```

```
class HealingItemsTable extends ItemsTable{
    const TYPE = 1;

    public function beforeFind(Event $event, Query $query, \ArrayObject $option, $primary){
        $query->where(['type' => self::TYPE]);
        return $query;
    }
}
```
- Create ItemsTable class.
- Create 4 Table class inherit ItemsTable like HealingItemsTable.

```
class HealingItem extends Item{
    public function someMedhotForHealingItem(){}
}
```

Same as Table class for entity classes.

This seams working good.
But I want to find better way.
### Q1

```
    public function beforeFind(Event $event, Query $query, \ArrayObject $option, $primary){
        parent::beforeFind($event, $query, $option, $primay); // Got error!
        $query->where(['type' => self::TYPE]);
        return $query;
    }
```

I got an error becase of no `beforeFind` method on `ItemsTable` class.
Is it not excpected that the Table class is to be super class?
### Q2

I want to retrieve 4 type of item entities from one ItemsTable.
`ItemsTable` returns a collection that contains several subclass of `Item` entity.
Some entites own original methods, but almost same interface as oop polymorphism.
It this possible with CakePHP3 ORM?

**Comment by HavokInspiration** [comment]
If I understand this correctly, it looks like you need the Single Table Inheritance pattern, which is not supported in the core yet.

@robertpustulka made a plugin available here that could help you do what you want : https://github.com/robotusers/cakephp-table-inheritance 

Edit : Also see https://github.com/cakephp/cakephp/issues/4412 for more reference

**Comment by kanonji** [comment]
Thank you for a reply.
I understand it is not supported currently.

That plugin seams to require each Table class.
As I will get similar result to the plugin, I prefer to have super class and sub classes if it is expected usage.
I want to keep my code base small.

If the plugin makes possible that one Table class returns several types of entity, It is really great.

**Comment by lorenzo** [comment]
There is currently no "Single Table Inheritance" feature in the Cake ORM. But if you create as many `Table` classes as different types you have, there it becomes quite trivial to do it.

``` php
class HealingItemsTable extends ItemsTable
{
    const TYPE = 1;

    public function initialize(array $config)
    {
        $this->entityClass(HealingItem::class);
        parent::initialize($config);
    }

    public function beforeFind(Event $event, Query $query, \ArrayObject $option, $primary){
        $query->where(['type' => self::TYPE]);
        return $query;
    }
}
```

## Q1

There is no `Table::beforeFind()`, so no need to call parent on direct descendants of the `Table` class.

## Q2

As I mentioned before, there is no "Single table inheritance" feature in the ORM. In general, I'm not too keen on the feature itself, as it is often difficult to work with and has little benefits.

**Comment by lorenzo** [comment]
@kanonji Btw, casting to another entity type can be done with ease using a `formatResults` callback in the parten table. Let me know if you need help getting that done

**Comment by kanonji** [comment]
@lorenzo 
Thank you for a reply.

Super class may have `beforeFind`.
I wanted to call `parent:: beforeFind()` from `beforeFind` medhot of sub class in case of that.
But I don't need to consider about it If there is anotehr way to get each entities from one Table class.
As you teach me, I tried `formatResults` to do so.
Can you please look through my code snipet below and tell me if there is something wrong?

```
class ItemsTable extends Table
{

    const HEALING = 10;
    const TICKET = 20;
    const LEVELING = 30;
    const GAME_KEY = 40;

//[snip]

    public function beforeFind(Event $event, Query $query, \ArrayObject $option, $primary)
    {
        $query->formatResults(function(ResultSetInterface $results){
            return $results->map(function($item) {
                switch($item->type){
                    case self::HEALING:
                        return new HealingItem($item->toArray());
                    case self::TICKET:
                        return new Ticket($item->toArray());
                    case self::LEVELING:
                        return new LevelingItem($item->toArray());
                    case self::GAME_Key:
                        return new KeyItem($item->toArray());
                }
                return $item;
            });
        });
        return $query;
    }
```

I'm feeling bit bad about `toArray()`.
Do I need to convert via array to cast entity type?

**Comment by kanonji** [comment]
Casting entity by `new HealingItem($item->toArray());` is failed.
This drops association.
I need to detach assosiations from `Item` entity and attach to `HealingItem` entity in some wise.

**Comment by lorenzo** [comment]
@kanonji Would you mind trying something like this? I have not tried it, but I think it could work nice:

``` php
public function castTo($class)
{
    $entity = new $class;
    foreach (get_object_vars($this) as $property => value) {
        $entity->{$property} = $value;
    }
    return $entity;
}
```

So the you could convert your entities to the right class on the fly:

``` php
$castedEntity = $item->castTo(HealingItem::class);
```

**Comment by kanonji** [comment]
@lorenzo Thank you for your help.

I tried your code.
Properties of the entity are in new entity casted including associations.
But there is a bit problem.
Accessors of new entity that is sub class can not be called.
That is because private/protected members are copied to new entity such as `$_className`, `$_original`.

To cast entity type, I think almost private/protected members should be copied.
Only `$_className`, `$_accessible` must no be copied, must leave members of the sub class.

I may fight to save the entity casted later.
In that saving, I guess I need to figure out which I should use between original one or casted one for `$_registryAlias`.
I may have white list to copy or black list to not copy.
But now I doubt that this is good approach or not.
Both white list and black list can not support new members that may be added in the future.

> As I mentioned before, there is no "Single table inheritance" feature in the ORM. In general, I'm not too keen on the feature itself, as it is often difficult to work with and has little benefits.

I want ask about this comment.
Do you think there are little benefits and a lot of difficulties to casting entity type with `castTo` method too?
I am asking because I want to solve this impedance mismatch with putting much value on model.
But I don't think I must split entities if there are no easy way.
I want take better practice(not best practice) for good design and speed for coding with CakePHP3 and its ORM.

**Comment by lorenzo** [comment]
I think using a whitelist or backlist of fields in that method can be used safely.

The biggest difficulty I see with casting entities is that you have to remember to do it in all finds. You can use a behavior for this if so you need.

In general I'm not happy with the idea of a table having different types of the same thing. In my mind is better to have different tables or use different table classes to query on the data.

**Comment by kanonji** [comment]
> In general I'm not happy with the idea of a table having different types of the same thing. In my mind is better to have different tables or use different table classes to query on the data.

Thank you for telling about design.
I tried about database design again to split tables. But I could not.
My modeling was changed like this `User hasMany UserItem belongsTo Item`.
I want to have 4 entitiy types of UserItem now.
UserItem can be kind of inventory. So I want this is a single table to retrieve all items which a player has.
But anyway, this is just because my design skill is not enough.

> The biggest difficulty I see with casting entities is that you have to remember to do it in all finds. You can use a behavior for this if so you need.

Sadly I can not understand what you mean.
`formatResults` to cast entity is set in `beforeFind` method.
So I think casting is auto in all finds, doesn't it?
As you will see, my English is not so good. I may be misunderstanding.
I would appreciate if you tell me bit more detail.

I put my code snippet hereunder just in case my explanation is confusing.

```
namespace App\Model\Entity;

trait CastingTrait
{
    public function castTo($class)
    {
        $entity = new $class;
        $excludes = ['_className', '_accessible'];
        foreach (get_object_vars($this) as $property => $value) {
            if (false === in_array($property, $excludes)) {
                $entity->{$property} = $value;
            }
        }
        return $entity;
    }
}
```

```
class UserItem extends Entity
{
    use CastingTrait;
[snip]
```

```
class UserHealingItem extends UserItem
class UserLevelingItem extends UserItem
class UserTicket extends UserItem
class UserPoint extends UserItem
```

```
namespace App\Model\Table;
[snip]
/**
 * UserItems Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Users
 * @property \Cake\ORM\Association\BelongsTo $Items
 */
class UserItemsTable extends Table
{
[snip]
    public function beforeFind(Event $event, Query $query, \ArrayObject $option, $primary)
    {
        $query->formatResults(function (CollectionInterface $results) {
            return $results->map(function ($userItem) {
                if (empty($userItem->item_type)) {
                    return $userItem;
                }
                switch ($userItem->item_type) {
                    case ItemsTable::HEALING:
                        return $userItem->castTo(UserHealingItem::CLASS);
                    case ItemsTable::TICKET:
                        return $userItem->castTo(UserTicket::CLASS);
                    case ItemsTable::LEVELING:
                        return $userItem->castTo(UserLevelingItem::CLASS);
                    case ItemsTable::POINT:
                        return $userItem->castTo(UserPoint::CLASS);
                }
                return $userItem;
            });
        });
        return $query;
    }
}
```

**Comment by lorenzo** [comment]
Your code looks like it would solve the problem very well. It could perhaps be packaged as a plugin?

**Comment by kanonji** [comment]
I'm relieved to hear that.
I will keep in mind to have each tables for different types.
And if I feel difficult to do so, I will try this casting method.
Thank you very much for your help.

> It could perhaps be packaged as a plugin?

The core of this casting method is only one trait. and that it is almost your code snippet.
Should I make this trait as a plugin?

**Comment by lorenzo** [comment]
It maybe be a good idea to put it in a plugin, or contribute it to another existing one

**Comment by kanonji** [comment]
Alright I will try it, though It takes time to learn some staffs for plugin like testing.
Thank you again.
