### ISSUE TITLE
Call to a member function clearContain() on null

### ISSUE THREAD

**Issue by kentosama** [cakephp/orm#5]
Hello, i want override contain with second parameter on "true" on my query, but CakePHP return fatal error : Call to a member function clearContain() on null

Here my query :

```
$feeds = $this->Feeds->find()
                ->contain([
                    'Users.Profiles.Avatars',
                    'Questions.Categories',
                    'Statuses',
                    'Cities',
                        ], true)
                ->where(['Users.username' => $this->request->data['username']])
                ->order(['Feeds.created' => 'DESC']);
```

I tested with some query and CakePHP return same error. What is the problem ?

Thank you !

**Comment by ADmad** [comment]
This issue was moved to cakephp/cakephp#7580
