### ISSUE TITLE
Hi，When I used in my project, it some error occurred

### ISSUE THREAD

**Issue by slince** [cakephp/orm#8]
![image](https://cloud.githubusercontent.com/assets/3785826/14132645/be72605c-f67a-11e5-938a-c57c0c2cfef2.png)

**Comment by ADmad** [comment]
Could you please require `cakephp/cache` in your `composer.json` and see if it fixes the issue.

**Comment by slince** [comment]
Yes, that will be fixed; @ADmad

**Comment by ADmad** [comment]
I presume you must have used `'cacheMetaData' => true` in your connection config. 

We probably need to improve the documentation stating that using metadata caching feature requires the `cakephp/cache` package which is not installed by default.

**Comment by htstudios** [comment]
Why is it not?

**Comment by lorenzo** [comment]
@jhli because the schema medatata can be injected. So I rather not force people into installing more dependencies.
