### ISSUE TITLE
Can use this ORM with symfony2 ?

### ISSUE THREAD

**Issue by Dosix** [cakephp/orm#9]
Hi,

It is possible to use this ORM with framework Symfony 2 ?

Best regards,
Ludovic

**Comment by lorenzo** [comment]
Yes, although there is no "Component" created for symfony yet. You can just do `composer require cakephp/orm` in your project and configure your connection as shown in the README.

**Comment by harikt** [comment]
@Dosix configuring cake/orm is easy to use with any framework. I have worked with it, so it is not a big deal. Lots of people eager and happy to help.

**Comment by Dosix** [comment]
Ok great to know, so i have another question, is it compatible with the doctrine's annotations ?

**Comment by josegonzalez** [comment]
We do not use doctrine annotations - CakePHP has generally stayed away from annotations - though I don't see why you could not add support for it.

**Comment by lorenzo** [comment]
What do you need the annotations for?

**Comment by Dosix** [comment]
Because we are using symfony2 as an API Rest and we have some plugins for display only datas we want.  For that we use this [JMS\Groups or JMS\SerializedName](http://jmsyst.com/bundles/JMSSerializerBundle)

Maybe we can do the same thing with `cakephp/orm` i don't remember.

**Comment by lorenzo** [comment]
I don't see why it wouldn't be possible for you to use the JMSS\Serializer with the ORM
